platformName: Android
deviceName: 192.168.3.26:5555
platformVersion: '9.0'
app: mind.apk
appPackage: com.mind_map_app
appActivity: com.reactnative_app.MainActivity
noReset: True  #False是重新安装 True是不重新安装
unicodeKeyboard: True
resetKeyboard: True
automationName: uiautomator2
ip: 127.0.0.1
port: 4723
#udid: FJH7N18925002809 # I7WCYT5H9SLNWCWG # FJH7N18925002809  FIG-TL00 127.0.0.1:62001